//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the MSBuild WriteCodeFragment class.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("ProcessServer.Tests", AllInternalsVisible = true)]
[assembly: InternalsVisibleTo("com.unity.process-server.tests", AllInternalsVisible = true)]
