{% metadata_file .yamato_config/config.yml %}
---
build:
  name: Build
  agent:
    type: Unity::VM
    image: core-kaunas/win10-vs2017-dotnetcore:latest
    flavor: m1.large
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

  commands:
    - powershell scripts\Get-Deps.ps1
    - npm install upm-ci-utils@stable -g --registry https://api.bintray.com/npm/unity/unity-npm
    - |
      set RELEASE=0
      if "x%GIT_TAG%"!==!"x" set RELEASE=1
      if "%RELEASE%"=="1" (pack -r -b -p -u) else (pack -r -b -u)

  artifacts:
    nuget:
      paths:
        - "build/nuget/**/*.nupkg"
        - "nuget.config"
    packman:
      paths:
        - "upm-ci~/**/*"
    binaries:
      paths:
        - "build/bin/**/*"
    tests:
      paths:
        - "build/tests/bin/**/*"
    sources:
      paths:
        - "build/upm/**/*"
